
version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: latest
    commands:
      - export PATH="$PATH:/root/.dotnet/tools"
      - dotnet tool install -g sleet
  build:
    commands:
      - dotnet pack -o .
      - sleet push d:\nupkgsToPush
