version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: latest
    commands:
      - export PATH="$PATH:/root/.dotnet/tools"
  build:
    commands:
      - dotnet build /p:Configuration=Release /p:OutDir=C:\codebuild\artifacts\ /p:Version='1.0.0'
      - dotnet pack -o .
      
artifacts:
  files:
    -'**/*'
  base-directory: 'C:\codebuild\artifacts\'
