version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: latest
    commands:
      - export PATH="$PATH:/root/.dotnet/tools"
  build:
    commands:
      - dotnet build --version-suffix '1.0.0'
      - dotnet pack -o C:\codebuild\artifacts\
      
artifacts:
  files:
    -'**/*'
  base-directory: 'C:\codebuild\artifacts\'
