
version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: latest
    commands:
      - export PATH="$PATH:/root/.dotnet/tools"
  build:
    commands:
      - dotnet pack -o .

artifacts:
 files:
   - '**/*'
 discard-paths: yes
